/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EstruturaCondicional;

public class App {
   
    public static void main(String[] args) {
        
        
        int media = 10;
        
        if(media >= 7){
            System.err.println("Aprovado");} 
        
        if(media ==10){
            System.err.println("Parabéns tirou nota maxima!!");} 
        else{
            System.err.println("Reprovado");}
       
    }
}
